name: Build Android APKs

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Build with Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        # يقوم هذا السكربت بإنشاء وتفعيل ملفات البناء آلياً حتى لو لم تكن موجودة
        arguments: assembleDebug
